---
abstract: 'tools for maintaining a perl mongers (webDav) website'
author:
  - 'Andrew Grangaard <spazm@cpan.org>'
build_requires:
  App::Cmd::Tester: 0
  Test::Class: 0
  Test::Class::Load: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-PM-Website
requires:
  App::Cmd: 0
  App::Cmd::Command: 0
  Config::YAML: 0
  Data::Dumper: 0
  Date::Parse: 0
  DateTime: 0
  DateTime::Format::Strptime: 0
  File::Path: 2.07
  File::Spec: 0
  HTTP::DAV: 0
  Lingua::EN::Numbers::Ordinate: 0
  Net::Netrc: 0
  POSIX: 0
  Template: 0
  Template::Plugin::DateTime: 0
  Template::Plugin::Gravatar: 0
  Template::Plugin::String::Compare: 0
  YAML::Any: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  homepage: http://lowlevelmanager.com/
  repository: http://github.com/spazm/app-pm-website.git
version: 0.122450
